### PR TITLE
Reinitialize variables in reconcile loop

### LINKED ISSUE #237: Error while creating API without interceptors after executing an API with interceptors
**Description:**
When try to create an API without interceptors after executing an API with interceptors it's giving following error while running the kaniko job.

ERROR: 
INFO[0098] args: [-c cp usr/wso2/libs/* ./project/lib/]
cp: can't stat 'usr/wso2/libs/*': No such file or directory
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by renuka-fernando**
fix #237 

- Reinitialize variables in reconcile loop

### CODE REVIEW

File: apim-operator/pkg/controller/api/api_controller.go [hunk 1]
```diff
@@ -514,36 +513,36 @@ func (r *ReconcileAPI) Reconcile(request reconcile.Request) (reconcile.Result, e
...
+				//copying default security to user namespace
+				log.Info("copying default security to " + userNameSpace)
+				newDefaultSecurity := copyDefaultSecurity(securityDefault, userNameSpace, owner)
+				errCreateSecurity := r.client.Create(context.TODO(), newDefaultSecurity)
+				if errCreateSecurity != nil {
+					log.Error(errCreateSecurity, "error creating secret for default security in user namespace")
+					return reconcile.Result{}, errCreateSecurity
+				}
+				log.Info("default security successfully copied to " + userNameSpace + " namespace")
+				if newDefaultSecurity.Spec.SecurityConfig[0].Issuer != "" {
```
Comment (dinusha92) [inline apim-operator/pkg/controller/api/api_controller.go]: Can SecurityConfig[0] be null? If that's the case, we may need handle this.

Comment (renuka-fernando) [reply apim-operator/pkg/controller/api/api_controller.go]: Updated the PR with reverting corrected formatting errors in other codes. Hence force pushed with only my changes.
