### PR TITLE
Remove global variables from registry package

### LINKED ISSUE #461: Error creating APIs concurrently
**Description:**
Error creating APIs concurrently. [operator-logs.tar.gz](https://github.com/wso2/k8s-api-operator/files/5323593/operator-logs.tar.gz)

**Suggested Solution:**
Move package level variables to functional variables. When two or more go routines read and write, append a package variable, operator will work as not expected.

**Steps to Reproduce:**

- Create 10 APIs concurrently
[internal doc](https://docs.google.com/document/d/1YnYKkr8ncknyo_fHUE1NG9OCwsEpiP04pCRdUaPuyJU/edit#)

**Affected Product Version:**
API Operator 1.2.0

### PR DESCRIPTION
**Pull request by feloy**
## Purpose

Because of global variables in the registry package, when the Operator restarts and several `API` resources exist, the operator will mix the image names between all APIs. As a result, all micro-gateways are deployed with the same image name (the one that was written last in the global variable)

I was able to test the case with  a GCR registry, but not with other registries.

Fixes #461

### CODE REVIEW

File: api-operator/pkg/registry/registry.go [hunk 1]
```diff
@@ -55,25 +55,30 @@ type Config struct {
...
+	//	dockerImage = img
 
-	return copyConfigVolumes(client, namespace)
+	return copyConfigVolumes(client, namespace, img)
 }
 
 // GetConfig returns the registry config
-func GetConfig() *Config {
-	return registryConfigs[dockerImage.RegistryType](dockerImage.RepositoryName, dockerImage.Name, dockerImage.Tag)
+//func GetConfig() *Config {
```
Comment (RakhithaRR) [inline api-operator/pkg/registry/registry.go:75]: Shall we remove these commented out code? There's commented out code in several places in this file.

**Review by RakhithaRR — CHANGES_REQUESTED** [review]

File: api-operator/pkg/registry/registry.go (hunk 1 above)
Comment (feloy) [reply api-operator/pkg/registry/registry.go:75]: Sorry this is not the latest changes I've made. I'll update them

Comment (feloy) [reply api-operator/pkg/registry/registry.go]: @RakhithaRR I've made the changes, there should be no more commented code anymore

**Review by RakhithaRR — APPROVED** [review]

File: api-operator/pkg/registry/http.go [hunk 2]
```diff
@@ -18,28 +18,29 @@ package registry
...
 	// Add --insecure arg
 	// This will not effect Docker Hub configs since this is a copy of it
 	httpReg.Args = []string{"--insecure"}
 	// replace https with http and use default function
-	httpReg.IsImageExist = func(config *Config, auth utils.RegAuth, image string, tag string) (b bool, err error) {
+	httpReg.IsImageExist = func(config *Config, auth utils.RegAuth, imageRepository string, imageName string, tag string) (b bool, err error) {
 		auth.RegistryUrl = strings.Replace(auth.RegistryUrl, "https://", "http://", 1)
 		logger.Info("Checking for image in HTTP registry", "Registry URL", auth.RegistryUrl)
-		return utils.IsImageExists(auth, getImageWithoutReg(image), tag)
+		return utils.IsImageExists(auth, "", imageName, tag)
```
Comment (renuka-fernando) [inline api-operator/pkg/registry/http.go:40]: In `docker-registry-config` we define `registryType` and  `repositoryName`.
Example: for private HTTP registry
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: wso2-system
data:
  registryType: HTTP
  repositoryName: 192.168.8.132:5000/apis-test
```

We assign the API name for the image name. So if we create an API named `pets` (version v1), the image is `192.168.8.132:5000/apis-test/pets:v1`

Hence:
- Repository: 192.168.8.132:5000/apis-test
- Image: pets
- Tag: v1

In this function (`utils.IsImageExists`), we have referred `apis-test/pets` as imageName in the current code (using the function `getImageWithoutReg`). But your changes referring it to `pets` (I think we have a confusion with current variable names). So the Docker registry API request is `"http://192.168.8.132:5000/v2/pets/tags/list"` instead of `"http://192.168.8.132:5000/v2/apis-test/pets/tags/list"` which should be corrected.

**Review by renuka-fernando — CHANGES_REQUESTED** [review]

**Review by renuka-fernando — APPROVED** [review]
Great!

**Review by pubudu538 — APPROVED** [review]
